services:
  postgres_paggo_ocr_case_db:
    image: postgres
    container_name: postgres_paggo_ocr_case_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - .env
    volumes: 
      - pg_paggo-ocr-case-db:/var/lib/postgresql/data

  node_paggo_ocr_case_app:
    container_name: node_paggo_ocr_case_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres_paggo_ocr_case_db
    env_file:
      - .env

volumes:
  pg_paggo-ocr-case-db: